---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1779572/public_html/ilhammuhammad.my.id
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -r images $DEPLOYPATH
